FROM        # Base image
WORKDIR     # Where we stand inside container
COPY        # Bring code/files inside the container
RUN         # Install or configure something
CMD         # Start the application
